### ISSUE TITLE
App downloaded from play store keeps crashing on Android 10

### ISSUE THREAD

**Issue by iarmankhan** [jvidalv/astrale#1]
Hey, went through the app and it's screenshots and I love the UI so decided to download it on my phone, but it's keep crashing after the initial info gathering.

I tried clearing data and all but it's same. 
Have a look on it

**Comment by iarmankhan** [comment]
Yes it's working now! Working really good, though there are some issues and that's because of expo (I guess) like white screen flashing on app startup, app freezing on ads etc.

**Comment by jvidalv** [comment]
Now the api will always return data even if it has none for the current day:
https://github.com/jvidalv/vvadmin/commit/759a73c129c8a0b44cee9383fe559e2d7f766389

And I also refactored some app code to get rid of the part thats was trying to catch this error, as it is not needed now. What I added is a new case when fetch is already done, and there is no data (No internet, etc...) and it shows a text string now, instead of crashing.
https://github.com/jvidalv/astrale/commit/8b46d07989ce69c7768717b7bfba76e2fbe73088

Thanks again for trying it!
